annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/kube-version: '>= v1.16.0-0 < v1.31.0-0'
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  #catalog.cattle.io/ui-version: '>= 2.7.2'
  catalog.cattle.io/ui-extension-version: '>= 2.0.0 < 3.0.0'
apiVersion: v2
appVersion: 2.0.1
description: OS Management extension
name: elemental
type: application
version: 2.0.1
icon: https://raw.githubusercontent.com/rancher/ui-plugin-charts/main/icons/elemental/2.0.1-icon-v2.svg
